modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="little_creatures"
version="${file.jarVersion}"
displayName="Little Creatures"
authors="Florian Tschimben"
description='''
A Minecraft Mod, that allows you to automate stuff using creatures
'''

[[dependencies.little_creatures]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.little_creatures]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"